// app/data/accessoriesData.tsx

const accessoriesData = [
  {
    image: "/honda-civic-2019.png",
    title: "Alloy Wheels",
    sub_title: "Premium Rims",
    feature1: "Set of 4",
    rating: 4.5, // ⭐⭐ New Rating
    price: "Price",
    amount_price: "PKR 800",
    sub_price: "PKR 1,000",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Leather Seat Covers",
    sub_title: "Luxury Feel",
    feature1: "Waterproof",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 150",
    sub_price: "PKR 200",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Audio Speakers",
    sub_title: "High Bass Sound",
    feature1: "4 Speakers",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 350",
    sub_price: "PKR 400",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Air Freshener",
    sub_title: "Luxury Perfume",
    feature1: "Long Lasting",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 20",
    sub_price: "PKR 30",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Steering Wheel Cover",
    sub_title: "Grip & Comfort",
    feature1: "Leather Finish",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 40",
    sub_price: "PKR 60",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Floor Mats",
    sub_title: "Durable Rubber",
    feature1: "Set of 5",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 70",
    sub_price: "PKR 90",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Dashboard Camera",
    sub_title: "HD Recording",
    feature1: "Night Vision",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 120",
    sub_price: "PKR 150",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Body Cover",
    sub_title: "All Weather Protection",
    feature1: "Waterproof",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 90",
    sub_price: "PKR 120",
  },
  {
    image: "/honda-civic-2019.png",
    title: "GPS Navigation System",
    sub_title: "Smart Display",
    feature1: "Voice Commands",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 300",
    sub_price: "PKR 350",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Portable Car Vacuum",
    sub_title: "Compact Cleaner",
    feature1: "Rechargeable",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 60",
    sub_price: "PKR 80",
  },
  {
    image: "/honda-civic-2019.png",
    title: "LED Headlights",
    sub_title: "Bright & Clear",
    feature1: "6000K White",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 180",
    sub_price: "PKR 220",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Battery Charger",
    sub_title: "Fast Charging",
    feature1: "12V/24V Support",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 100",
    sub_price: "PKR 130",
  },
];

export default accessoriesData;
