// app/HomePage/carsData.ts
export interface Car {
  image: string;
  title: string;
  sub_title: string;
  num: number;
  num2: string;
  num3: string;
  price: string;
  amount_price: string;
  sub_price: string;
}

export const carsData: Car[] = [
  {
    image: "/car1.png",
    title: "Tesla Model S",
    sub_title: "Electric Sedan",
    num: 5,
    num2: "Electric",
    num3: "250 km/h",
    price: "price",
    amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "BMW X5",
    sub_title: "Luxury SUV",
    num: 7,
    num2: "Petrol",
    num3: "240 km/h",
    price: "price",
    amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Range Rover Evoque",
    sub_title: "Offroad Beast",
    num: 5,
    num2: "Diesel",
    num3: "220 km/h",
    price: "price",
     amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Ferrari 488",
    sub_title: "Sports Car",
    num: 2,
    num2: "Petrol",
    num3: "330 km/h",
    price: "price",
     amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Audi A8",
    sub_title: "Executive Sedan",
    num: 5,
    num2: "Hybrid",
    num3: "260 km/h",
    price: "price",
    amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Lamborghini Huracan",
    sub_title: "Supercar",
    num: 2,
    num2: "Petrol",
    num3: "340 km/h",
    price: "price",
     amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Mercedes G-Wagon",
    sub_title: "Luxury SUV",
    num: 7,
    num2: "Diesel",
    num3: "210 km/h",
    price: "price",
     amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Porsche 911",
    sub_title: "Iconic Coupe",
    num: 4,
    num2: "Petrol",
    num3: "320 km/h",
    price: "price",
    amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Toyota Supra",
    sub_title: "JDM Legend",
    num: 2,
    num2: "Petrol",
    num3: "280 km/h",
    price: "price",
     amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Nissan GTR",
    sub_title: "Godzilla",
    num: 4,
    num2: "Petrol",
    num3: "310 km/h",
    price: "price",
    amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Bugatti Chiron",
    sub_title: "Fastest Car",
    num: 2,
    num2: "Petrol",
    num3: "420 km/h",
    price: "price",
     amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
  {
    image: "/car1.png",
    title: "Ford Mustang",
    sub_title: "American Muscle",
    num: 4,
    num2: "Petrol",
    num3: "260 km/h",
    price: "price",
     amount_price: "PKR 80,000",
    sub_price: "Pk90,000",
  },
];
